//
//  Location.swift
//  CiaoNaples
//
//  Created by Edgar Ernesto Vergara Montiel on 18/10/23.
//

import Foundation

struct Location: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let coverImage: String
    let images: [String]
    let description: String
    let zone: String
    let tips: [String]
    let latitude: Double
    let longitude: Double
    let category: Category
}

extension Location {
    static let locations = [
        // Food
        Location(name: "Place 1", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .food),
        Location(name: "Place 2", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .food),
        Location(name: "Place 3", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .food),
        Location(name: "Place 4", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .food),
        Location(name: "Place 5", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .food),
        
        // Drinks
        Location(name: "Place 1", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .drinks),
        Location(name: "Place 2", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .drinks),
        Location(name: "Place 3", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .drinks),
        Location(name: "Place 4", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .drinks),
        Location(name: "Place 5", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .drinks),
        
        // Daily Life
        Location(name: "Place 1", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife),
        Location(name: "Place 2", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife),
        Location(name: "Place 3", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife),
        Location(name: "Place 4", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife),
        Location(name: "Place 5", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife),
        
        // Museums
        Location(name: "Place 1", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .museums),
        Location(name: "Place 2", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .museums),
        Location(name: "Place 3", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .museums),
        Location(name: "Place 4", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .museums),
        Location(name: "Place 5", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .museums),
        
        // Gardens
        Location(name: "Place 1", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .gardens),
        Location(name: "Place 2", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .gardens),
        Location(name: "Place 3", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .gardens),
        Location(name: "Place 4", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .gardens),
        Location(name: "Place 5", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .gardens),
        
        // Viewpoints
        Location(name: "Place 1", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .viewpoints),
        Location(name: "Place 2", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .viewpoints),
        Location(name: "Place 3", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .viewpoints),
        Location(name: "Place 4", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .viewpoints),
        Location(name: "Place 5", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .viewpoints),
        
        // Folkloric Places
        Location(name: "Place 1", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .folkloricPlaces),
        Location(name: "Place 2", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .folkloricPlaces),
        Location(name: "Place 3", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .folkloricPlaces),
        Location(name: "Place 4", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .folkloricPlaces),
        Location(name: "Place 5", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .folkloricPlaces),
    ]
}
