//
//  Location.swift
//  CiaoNaples
//
//  Created by Edgar Ernesto Vergara Montiel on 18/10/23.
//

import Foundation

struct Location: Identifiable, Hashable {
    let id = UUID().uuidString
    let name: String
    let coverImage: String
    let images: [String]
    let description: String
    let zone: String
    let tips: [String]
    let latitude: Double
    let longitude: Double
    let category: Category
    var tag: String?
//    let topChoice: Bool
//    let publicTransport: Bool
//    let ticketNeeded: Bool?
//    let cheapChoice: Bool?
    
}

extension Location {
    static let locations = [
        // Food And Drinks
        // Food
        Location(name: "Food 1", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .foodAndDrinks, tag: "Food"),
        Location(name: "Food 2", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .foodAndDrinks, tag: "Food"),
        Location(name: "Food 3", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .foodAndDrinks, tag: "Food"),
        Location(name: "Food 4", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .foodAndDrinks, tag: "Food"),
        Location(name: "Food 5", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .foodAndDrinks, tag: "Food"),
        
        // Drinks
        Location(name: "Drink 1", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .foodAndDrinks, tag: "Drinks"),
        Location(name: "Drink 2", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .foodAndDrinks, tag: "Drinks"),
        Location(name: "Drink 3", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .foodAndDrinks, tag: "Drinks"),
        Location(name: "Drink 4", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .foodAndDrinks, tag: "Drinks"),
        Location(name: "Drink 5", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .foodAndDrinks, tag: "Drinks"),
        
        // Daily Life
        // Day
        Location(name: "Day 1", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife, tag: "Day"),
        Location(name: "Day 2", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife, tag: "Day"),
        Location(name: "Day 3", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife, tag: "Day"),
        Location(name: "Day 4", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife, tag: "Day"),
        Location(name: "Day 5", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife, tag: "Day"),
        
        // Night
        Location(name: "Night 1", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife, tag: "Night"),
        Location(name: "Night 2", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife, tag: "Night"),
        Location(name: "Night 3", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife, tag: "Night"),
        Location(name: "Night 4", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife, tag: "Night"),
        Location(name: "Night 5", coverImage: "cover_image", images: ["image1, image2, image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .dailyLife, tag: "Night"),
        
        // Viewpoints
        Location(name: "Viewpoint 1", coverImage: "cover_image", images: ["image1", "image2", "image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .viewpoints),
        Location(name: "Viewpoint 2", coverImage: "cover_image", images: ["image1", "image2", "image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .viewpoints),
        Location(name: "Viewpoint 3", coverImage: "cover_image", images: ["image1", "image2", "image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .viewpoints),
        Location(name: "Viewpoint 4", coverImage: "cover_image", images: ["image1", "image2", "image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .viewpoints),
        Location(name: "Viewpoint 5", coverImage: "cover_image", images: ["image1", "image2", "image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .viewpoints),
        
        // Folkloric Places
        Location(name: "Fokloric Place 1", coverImage: "cover_image", images: ["image1", "image2", "image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .folkloricPlaces),
        Location(name: "Fokloric Place 2", coverImage: "cover_image", images: ["image1", "image2", "image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .folkloricPlaces),
        Location(name: "Fokloric Place 3", coverImage: "cover_image", images: ["image1", "image2", "image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .folkloricPlaces),
        Location(name: "Fokloric Place 4", coverImage: "cover_image", images: ["image1", "image2", "image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .folkloricPlaces),
        Location(name: "Fokloric Place 5", coverImage: "cover_image", images: ["image1", "image2", "image3"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", zone: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", tips: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: .folkloricPlaces),
    ]
}
