//
//  Location.swift
//  CiaoNaples
//
//  Created by Edgar Ernesto Vergara Montiel on 18/10/23.
//

import Foundation

struct Location: Identifiable, Hashable, Codable {
    let id: String
    let name: String
    let coverImage: String
    let images: [String]
    let locDescription: String
    let recommendations: [String]
    let latitude: Double
    let longitude: Double
    let category: Int
    var tag: String?
    var topChoice: Bool
    var publicTransport: Bool
    var ticketNeeded: Bool?
    var cheapChoice: Bool
}

extension Location {
    static let locations = [
        // Food And Drinks
        // Food
        Location(id: "1", name: "Food 1", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.foodAndDrinks.id, tag: "Food", topChoice: true, publicTransport: true, cheapChoice: true),
        Location(id: "2", name: "Food 2", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.foodAndDrinks.id, tag: "Food", topChoice: false, publicTransport: false, cheapChoice: true),
        Location(id: "3", name: "Food 3", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.foodAndDrinks.id, tag: "Food", topChoice: false, publicTransport: true, cheapChoice: true),
        Location(id: "4", name: "Food 4", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.foodAndDrinks.id, tag: "Food", topChoice: true, publicTransport: false, cheapChoice: false),
        Location(id: "5", name: "Food 5", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.foodAndDrinks.id, tag: "Food", topChoice: false, publicTransport: false, cheapChoice: false),
        
        // Drinks
        Location(id: "6", name: "Drink 1", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.foodAndDrinks.id, tag: "Drinks", topChoice: true, publicTransport: true, cheapChoice: true),
        Location(id: "7", name: "Drink 2", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.foodAndDrinks.id, tag: "Drinks", topChoice: false, publicTransport: false, cheapChoice: true),
        Location(id: "8", name: "Drink 3", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.foodAndDrinks.id, tag: "Drinks", topChoice: false, publicTransport: true, cheapChoice: true),
        Location(id: "9", name: "Drink 4", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.foodAndDrinks.id, tag: "Drinks", topChoice: true, publicTransport: false, cheapChoice: false),
        Location(id: "10", name: "Drink 5", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.foodAndDrinks.id, tag: "Drinks", topChoice: false, publicTransport: false, cheapChoice: false),
        
        // Daily Life
        // Day
        Location(id: "11", name: "Day 1", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.dailyLife.id, tag: "Day", topChoice: false, publicTransport: true, ticketNeeded: true, cheapChoice: true),
        Location(id: "12", name: "Day 2", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.dailyLife.id, tag: "Day", topChoice: true, publicTransport: false, ticketNeeded: true, cheapChoice: false),
        Location(id: "13", name: "Day 3", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.dailyLife.id, tag: "Day", topChoice: false, publicTransport: true, ticketNeeded: false, cheapChoice: false),
        Location(id: "14", name: "Day 4", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.dailyLife.id, tag: "Day", topChoice: true, publicTransport: false, ticketNeeded: false, cheapChoice: false),
        Location(id: "15", name: "Day 5", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.dailyLife.id, tag: "Day", topChoice: false, publicTransport: false, ticketNeeded: false, cheapChoice: true),
        
        // Night
        Location(id: "16", name: "Night 1", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.dailyLife.id, tag: "Night", topChoice: true, publicTransport: true, ticketNeeded: true, cheapChoice: false),
        Location(id: "17", name: "Night 2", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.dailyLife.id, tag: "Night", topChoice: false, publicTransport: true, ticketNeeded: true, cheapChoice: true),
        Location(id: "18", name: "Night 3", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.dailyLife.id, tag: "Night", topChoice: false, publicTransport: false, ticketNeeded: true, cheapChoice: true),
        Location(id: "19", name: "Night 4", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.dailyLife.id, tag: "Night", topChoice: true, publicTransport: false, ticketNeeded: false, cheapChoice: true),
        Location(id: "20", name: "Night 5", coverImage: "cover_image", images: ["image1, image2, image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.dailyLife.id, tag: "Night", topChoice: true, publicTransport: true, ticketNeeded: false, cheapChoice: false),
        
        // Viewpoints
        Location(id: "21", name: "Viewpoint 1", coverImage: "cover_image", images: ["image1", "image2", "image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.viewpoints.id, topChoice: true, publicTransport: false, ticketNeeded: true, cheapChoice: true),
        Location(id: "22", name: "Viewpoint 2", coverImage: "cover_image", images: ["image1", "image2", "image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.viewpoints.id, topChoice: false, publicTransport: true, ticketNeeded: true, cheapChoice: true),
        Location(id: "23", name: "Viewpoint 3", coverImage: "cover_image", images: ["image1", "image2", "image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.viewpoints.id, topChoice: true, publicTransport: true, ticketNeeded: false, cheapChoice: true),
        Location(id: "24", name: "Viewpoint 4", coverImage: "cover_image", images: ["image1", "image2", "image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.viewpoints.id, topChoice: false, publicTransport: false, ticketNeeded: true, cheapChoice: true),
        Location(id: "25", name: "Viewpoint 5", coverImage: "cover_image", images: ["image1", "image2", "image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.viewpoints.id, topChoice: false, publicTransport: true, ticketNeeded: true, cheapChoice: false),
        
        // Folkloric Places
        Location(id: "26", name: "Fokloric Place 1", coverImage: "cover_image", images: ["image1", "image2", "image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.folkloricPlaces.id, topChoice: true, publicTransport: true, ticketNeeded: false, cheapChoice: true),
        Location(id: "27", name: "Fokloric Place 2", coverImage: "cover_image", images: ["image1", "image2", "image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.folkloricPlaces.id, topChoice: true, publicTransport: false, ticketNeeded: true, cheapChoice: true),
        Location(id: "28", name: "Fokloric Place 3", coverImage: "cover_image", images: ["image1", "image2", "image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.folkloricPlaces.id, topChoice: false, publicTransport: false, ticketNeeded: false, cheapChoice: true),
        Location(id: "29", name: "Fokloric Place 4", coverImage: "cover_image", images: ["image1", "image2", "image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.folkloricPlaces.id, topChoice: true, publicTransport: true, ticketNeeded: true, cheapChoice: true),
        Location(id: "30", name: "Fokloric Place 5", coverImage: "cover_image", images: ["image1", "image2", "image3"], locDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In maximus molestie ultricies. Suspendisse auctor at risus id sodales. In hac habitasse platea dictumst", recommendations: ["recommendation 1", "recommendation 2", "recommendation 3"], latitude: 40.849751, longitude: 14.263419, category: Category.folkloricPlaces.id, topChoice: false, publicTransport: true, ticketNeeded: false, cheapChoice: true),
    ]
}
